version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    command: python manage.py runserver 0.0.0.0:3005
    image: web:django
    container_name: django_container