name: Django CI

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v1
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        name: Caching files and dependencies
        uses: actions/cache@v2
        with:
          #path: ~/.cache/pip
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-pip-${{ hashFiles('setup.py') }}-pip-${{ hashFiles('**/requirements.txt') }}
          #restore-keys: |
            #${{ runner.os }}-pip-
      -
        name: Install dependencies
        #if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Run tests
        run: python -m pytest