name: Django CI

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

# We could also create an actions to a specific branch or pull request with:
# on:
  # push:
    # branches: [ master ]
  # pull_request:
    # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v1
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        #if: steps.cacheStep.outputs.cache-hit != 'true'
      -
        name: Run tests
        run: python -m pytest